x-common-variables: &common-variables
  ConnectionStrings__DefaultConnection: "Server=database;Database=BankDb;User Id=sa;Password=BankAppPassword123!;TrustServerCertificate=True"
  JWT__Key: "#U?(/7lTxB#S+J(io1x-ChnS}y8@MO(cMNCg3QRO2.OKspLby0v5mhhvh[xJ-6}L"
  JWT__Issuer: "BankApp"
  JWT__Audience: "BankApp"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bankapp-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BankAppPassword123!
    ports:
      - "1433:1433"
    networks:
      - bank-net

  blazorapp:
    image: ${DOCKER_REGISTRY-}blazorapp
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile
    depends_on:
      - database
    ports:
      - "7001:8080" # Everything (UI + API) is now on port 7001
    environment:
      <<: *common-variables
    networks:
      - bank-net

networks:
  bank-net:
    driver: bridge