services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bankapp-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pa$$w0rd!
    ports:
      - "1433:1433"
    volumes:
      - D:/Desktop/mssql/data:/var/opt/mssql/data
      - D:/Desktop/mssql/log:/var/opt/mssql/log
      - D:/Desktop/mssql/secrets:/var/opt/mssql/secrets
    networks:
      - bank-network

  web:
    build:
      context: .
      dockerfile: BankApp/Dockerfile
    container_name: bankapp-web
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BankAppDb;User Id=sa;Password=Pa$$w0rd!;TrustServerCertificate=True
    ports:
      - "8080:8080"
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge